<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Use Google reCAPTCHA (a challenge tha_d7b3d0</name>
   <tag></tag>
   <elementGuidId>2490ddac-4fea-4186-95b0-6013ded8e1f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#use_SPAM_FILTER_AKISMET</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='use_SPAM_FILTER_AKISMET']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9174d3f8-3cef-4140-8c27-1ce2a1ea1349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e51b7bc1-e8eb-4ff4-81c3-cb10bce2ab69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switch-a</value>
      <webElementGuid>cd0a5710-4924-4ea2-8b51-e0b9f8cc4884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[Form][use_SPAM_FILTER_AKISMET]</value>
      <webElementGuid>a211c355-f985-4296-8799-84fcf9bc6aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>use_SPAM_FILTER_AKISMET</value>
      <webElementGuid>82e3e81c-d2d6-4d00-bc04-9e365946cf06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>13f438ef-53c7-40a4-bad3-ed69e7670554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>0da00b26-9f18-47a5-9127-d1664be8a619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;use_SPAM_FILTER_AKISMET&quot;)</value>
      <webElementGuid>b267cae5-e2de-4cc5-82ec-ca2fabc6cc91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='use_SPAM_FILTER_AKISMET']</value>
      <webElementGuid>4e39d32f-0c9f-4546-800f-9b718ba27fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='processing-options-form']/div/fieldset[5]/div[2]/input</value>
      <webElementGuid>547dbdec-f7f1-4057-a068-50da57f556a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[5]/div[2]/input</value>
      <webElementGuid>cf6eab3f-8280-4246-9091-835d1cec3dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'data[Form][use_SPAM_FILTER_AKISMET]' and @id = 'use_SPAM_FILTER_AKISMET' and @checked = 'checked']</value>
      <webElementGuid>be3979dc-5aa9-4f8b-841e-6020250bacc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
