<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_8ZJnc48agp</name>
   <tag></tag>
   <elementGuidId>cc179a5e-f366-425a-960c-83a77b92c968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#8ZJnc48agp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='8ZJnc48agp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4d40d4d-1c8d-450a-a063-4c8848a93c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>5b299926-7598-4215-851e-9bb32f87acdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8ZJnc48agp</value>
      <webElementGuid>6be3774e-a019-4888-945d-ad266acae547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>7db1cc32-d700-4d9b-943f-21e6fc016af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16ac56c2-e266-4e0e-a8a7-ae817af5c658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8ZJnc48agp&quot;)</value>
      <webElementGuid>f0bb2c25-42a9-41d4-b587-b6bae3b54dfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='8ZJnc48agp']</value>
      <webElementGuid>25df50f8-6af8-4c1f-97a8-ca86d176a3d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='YOdC7HmlE-slds-tabs_panel-0']/div/div[3]/div/div/input</value>
      <webElementGuid>47046e8a-b3f7-4ffd-b5f3-f208db33ddf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>9e92ae18-5fe1-4d89-9ced-cf86096bef72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '8ZJnc48agp' and @placeholder = 'Search' and @type = 'text']</value>
      <webElementGuid>aca44a9c-20c0-4637-9e0d-8c6b1264be77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
