<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_This custom message which will be dis_9a4b08</name>
   <tag></tag>
   <elementGuidId>b5f55f36-d4ce-4d2b-8c13-01adc58051b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#processing-options-form-submit-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='processing-options-form-submit-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67354528-638d-4cab-9d93-c4fe65162dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>15523fb6-24ab-4da9-bdba-1165c30cb862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>d69a3cda-4df6-42a8-98da-ca1a098004f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primaryAction slds-button slds-button--brand full-width</value>
      <webElementGuid>24ebfcf2-d35b-4fe4-bc2f-b049d47950e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>processing-options-form-submit-button</value>
      <webElementGuid>ffddbfa4-41e4-492d-a2a0-9b04d59195da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;processing-options-form-submit-button&quot;)</value>
      <webElementGuid>9395dab6-cb10-48ba-b32f-1a10896d9de4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='processing-options-form-submit-button']</value>
      <webElementGuid>bb0606bb-5e82-4afe-b6a8-0f9a6f29fbf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='processing-options-form']/div/div[2]/input[2]</value>
      <webElementGuid>a7ac2429-a519-488c-bb34-b73848a20a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>828075eb-f049-4812-b5a8-ad2e0b7a9f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'processing-options-form-submit-button']</value>
      <webElementGuid>41607dc9-b657-472b-bccd-69d85b5033ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
