<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Processing</name>
   <tag></tag>
   <elementGuidId>6c0ccc34-2176-43aa-92dd-08f6b1cfd976</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='side-nav']/div[2]/li/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>309dfb65-ee6b-44c7-8bab-65fd1d3f5e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>side-navigation__action-text slds-m-left--x-small</value>
      <webElementGuid>d428ab4b-c29f-4550-93ec-70e72207507c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Processing</value>
      <webElementGuid>03ed2ccd-3a32-4519-93cd-18a57e6dddcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Processing</value>
      <webElementGuid>dd6236d9-b0f4-42b0-b723-d8641e9872ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-nav&quot;)/div[@class=&quot;slds-nav-vertical__section slds-m-top--small&quot;]/li[@class=&quot;slds-nav-vertical__item&quot;]/a[@class=&quot;side-navigation__action slds-nav-vertical__action slds-p-vertical--small&quot;]/span[@class=&quot;side-navigation__action-text slds-m-left--x-small&quot;]</value>
      <webElementGuid>4f8a7505-24dc-43d0-a66a-eb5f98d85a23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='side-nav']/div[2]/li/a/span[2]</value>
      <webElementGuid>29abe1b4-7ed2-42b4-bd32-cef6744b0b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options'])[1]/following::span[2]</value>
      <webElementGuid>b6bae651-7741-4d48-936e-2d323312fb9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responses'])[1]/following::span[2]</value>
      <webElementGuid>5bff6ec8-33a5-401c-ac92-c52fec1b14d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/preceding::span[2]</value>
      <webElementGuid>25b5ad7c-a5f1-4553-a4cc-cd0656e7e526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connectors'])[1]/preceding::span[4]</value>
      <webElementGuid>a46faf76-78f9-4b77-84fb-a27f97b019c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Processing']/parent::*</value>
      <webElementGuid>5c5793d0-18c5-4707-8009-0fabf29742b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/li/a/span[2]</value>
      <webElementGuid>a5e6c734-69a0-450f-941c-97ce604814f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Processing' or . = 'Processing')]</value>
      <webElementGuid>d27eea51-fad9-4004-baac-e6703d02c85b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
