<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Summary</name>
   <tag></tag>
   <elementGuidId>e83b0f51-ec54-4405-a49f-9e28f793d6e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='side-nav']/li[2]/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>27b52729-7cd0-420d-9454-a19694326f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>side-navigation__action-text slds-m-left--x-small</value>
      <webElementGuid>ada50b9b-2438-4363-981f-e3753b525c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Summary</value>
      <webElementGuid>dc247739-b49f-42c0-8dcc-f59999a3c28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Summary</value>
      <webElementGuid>52c18508-db3b-4c8c-9383-238afdf8d9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-nav&quot;)/li[@class=&quot;slds-nav-vertical__item&quot;]/a[@class=&quot;side-navigation__action slds-nav-vertical__action slds-p-vertical--small&quot;]/span[@class=&quot;side-navigation__action-text slds-m-left--x-small&quot;]</value>
      <webElementGuid>b7ec65cc-e6d5-4f72-9761-8db1c7818b56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='side-nav']/li[2]/a/span[2]</value>
      <webElementGuid>01329128-632b-4e07-963b-8d3d92c38890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forms List'])[1]/following::span[2]</value>
      <webElementGuid>a20d0835-0ab1-4fe5-9e08-6c86f5f3283e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Builder'])[1]/preceding::span[2]</value>
      <webElementGuid>655de2ef-e568-4798-ba45-763b5c38e25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::span[4]</value>
      <webElementGuid>bacfa5b4-8299-4151-92b7-77703c424b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Summary']/parent::*</value>
      <webElementGuid>e078a545-0ab8-46a0-b1cc-e918a80fa18f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span[2]</value>
      <webElementGuid>910c5de0-de4c-4a84-850e-410b5b470bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Summary' or . = 'Summary')]</value>
      <webElementGuid>9179b48f-aaa9-44cb-95a8-f80ed1474977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
