<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TESTPP</name>
   <tag></tag>
   <elementGuidId>9e6d3a98-881f-436e-8e07-de3cb32c722e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>button.boxclose</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>span</name>
      <type>Main</type>
      <value>CLOSE</value>
   </webElementProperties>
</WebElementEntity>
