<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CaptchaButton</name>
   <tag></tag>
   <elementGuidId>809b94a3-15c9-41a6-9628-998641dbb1aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='processing-options-form-submit-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#processing-options-form-submit-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33deef24-b184-40fc-8e1f-78828fbdf7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0afa8d1c-a220-4760-b547-a807b47cdccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>9f6c3044-073a-4914-b4bb-43da852f588e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primaryAction slds-button slds-button--brand full-width</value>
      <webElementGuid>5b0549e8-fc13-421b-b8b9-dafa5c542ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>processing-options-form-submit-button</value>
      <webElementGuid>e51de7ab-1cbc-4311-80b5-4aa38637c373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;processing-options-form-submit-button&quot;)</value>
      <webElementGuid>bc698a33-2bf8-4afc-85f4-54d1d1b2ad16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='processing-options-form-submit-button']</value>
      <webElementGuid>647769eb-0fb2-4c48-b04a-adc6fc41d368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='processing-options-form']/div/div[2]/input[2]</value>
      <webElementGuid>500623dc-46f0-47e1-8d9f-0fb7fb754df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>e5d161e8-c97c-4b7f-abc9-1c8b41f2520a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'processing-options-form-submit-button']</value>
      <webElementGuid>e005ee03-a6c8-4834-98f3-fc47428eda52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
