<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Spam filter options_dataFormuse_SPAM__063f21</name>
   <tag></tag>
   <elementGuidId>9ef873d1-a785-4eba-9544-692c0dfb6f6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkboxUseSpamFilter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkboxUseSpamFilter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f8851bf-f0bb-40bc-b9ed-af6b93d7d2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>814a05e9-65d5-4c4e-9781-f16ece3a2238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[Form][use_SPAM_FILTER_CAPTCHA]</value>
      <webElementGuid>5ad8fda2-a043-45c4-9985-dabf6e053a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkboxUseSpamFilter</value>
      <webElementGuid>d330c057-f698-4ce8-be2b-eb79e81374d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4298c3be-ac6a-44fa-939a-677d76970665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>8e79a13d-f4d1-4579-9f4c-a5f82a1aec53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkboxUseSpamFilter&quot;)</value>
      <webElementGuid>acd834a1-5f51-4c43-8da8-68510d100de7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkboxUseSpamFilter']</value>
      <webElementGuid>c8e5cedd-88b8-402b-b0e2-9b29c2cbb3fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='processing-options-form']/div/fieldset[5]/div/input</value>
      <webElementGuid>8a5826cb-e126-4634-a66c-cd6b5bea8bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[5]/div/input</value>
      <webElementGuid>01feb7e3-0395-4856-aae9-1c1179d73d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'data[Form][use_SPAM_FILTER_CAPTCHA]' and @id = 'checkboxUseSpamFilter' and @checked = 'checked']</value>
      <webElementGuid>c9bd0075-c065-4331-9c19-b4341f82b451</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
