<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Spam filter options_dataFormuse_SPAM__063f21_1</name>
   <tag></tag>
   <elementGuidId>10e4ad33-7dc2-48ff-a4ca-418d77e37ed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkboxUseSpamFilter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkboxUseSpamFilter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13aa1e1d-ab50-4440-a7a3-e5057151865f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8f111f6d-79e7-4b8e-94bb-749f239b14c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[Form][use_SPAM_FILTER_CAPTCHA]</value>
      <webElementGuid>73556196-934e-4fc9-895a-4bc792039ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkboxUseSpamFilter</value>
      <webElementGuid>159b5506-a643-4b7f-b85b-7690179c565d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5a2aa5b0-0d74-4180-b549-b88f226b5cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkboxUseSpamFilter&quot;)</value>
      <webElementGuid>3bc063a4-2cb8-4f4c-9efb-68ba71a61d81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkboxUseSpamFilter']</value>
      <webElementGuid>29fbeebd-f58f-4c27-8fd2-91018981c1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='processing-options-form']/div/fieldset[5]/div/input</value>
      <webElementGuid>f94839c3-84f7-4b7b-a7d6-68574818d57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[5]/div/input</value>
      <webElementGuid>4fce721b-150c-4948-8b7e-d66cbbd62d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'data[Form][use_SPAM_FILTER_CAPTCHA]' and @id = 'checkboxUseSpamFilter']</value>
      <webElementGuid>43d9c90b-e33f-466f-ab47-d1ed6c9f9498</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
