<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Use Google reCAPTCHA (a challenge tha_d7b3d0</name>
   <tag></tag>
   <elementGuidId>bc56b315-d3da-434a-a35e-cb8878ea562d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#use_SPAM_FILTER_AKISMET</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='use_SPAM_FILTER_AKISMET']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6669d636-157a-49df-8d7a-26fe576c3de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c184a1c9-53a0-41b2-8ec4-803309eec98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switch-a</value>
      <webElementGuid>ca9efc86-6b67-4f35-8a46-4629ca4c32d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[Form][use_SPAM_FILTER_AKISMET]</value>
      <webElementGuid>62121af7-a2ad-4c6a-a0e3-f218cc306f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>use_SPAM_FILTER_AKISMET</value>
      <webElementGuid>db7a3dbf-76b4-4c1c-a9cf-73067d3eb3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>abd24b18-05ed-4a7c-9957-bd61a3de4837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>d04b7393-19f5-4fa0-ad03-5e4b6ea5b816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;use_SPAM_FILTER_AKISMET&quot;)</value>
      <webElementGuid>f7ee4fd3-6388-4a33-b05c-47c31b587659</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='use_SPAM_FILTER_AKISMET']</value>
      <webElementGuid>0deff749-d7da-4cb4-a4c7-f6f4542d751c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='processing-options-form']/div/fieldset[5]/div[2]/input</value>
      <webElementGuid>028dbdc2-e947-45fa-bfd1-ed148b6fa77c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[5]/div[2]/input</value>
      <webElementGuid>393c41a6-3ef7-47be-b7a2-2828e828e4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'data[Form][use_SPAM_FILTER_AKISMET]' and @id = 'use_SPAM_FILTER_AKISMET' and @checked = 'checked']</value>
      <webElementGuid>05f09155-0a6e-4be5-9abe-22201fb1cba4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
