<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_itZdZb-S0v</name>
   <tag></tag>
   <elementGuidId>94520332-631d-41b7-9ce4-2c2ede857b44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itZdZb-S0v</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='itZdZb-S0v']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09baa0d5-06a8-4598-a391-5d26b94e09ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>a67d95c6-4c8b-44a3-881e-03a545b72dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itZdZb-S0v</value>
      <webElementGuid>81b4534f-c73d-4572-852b-7f4c8967f330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>544540df-eee5-41f1-a8d8-fe7f40164902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ac2ba465-d753-470d-a37d-3d3b39ab613d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itZdZb-S0v&quot;)</value>
      <webElementGuid>3ebc1be1-69bb-4aa5-a604-b7a74c4c407d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='itZdZb-S0v']</value>
      <webElementGuid>7ed84613-fa1f-45ca-852f-bd2c7996250f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ML96erJx--slds-tabs_panel-0']/div/div[3]/div/div/input</value>
      <webElementGuid>48855d11-3aec-4eb0-9133-8cc973a64701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>3a745deb-94d4-4810-8435-2a15a7eab634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'itZdZb-S0v' and @placeholder = 'Search' and @type = 'text']</value>
      <webElementGuid>6566d5ce-ba34-405b-a99a-f6e0ddd3f79a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
