<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_This custom message which will be dis_9a4b08</name>
   <tag></tag>
   <elementGuidId>45b10efb-046f-402d-8fe2-fd4f8fa727f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#processing-options-form-submit-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='processing-options-form-submit-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49ab815b-57ae-40ea-8472-cf38c70ad6f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2e12d9a5-6941-4a98-a621-b1f334d61dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>9f6a1bf5-4479-4989-91da-a1a15d0ccac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primaryAction slds-button slds-button--brand full-width</value>
      <webElementGuid>8dd51384-963f-4db5-9e4c-eae0c3670525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>processing-options-form-submit-button</value>
      <webElementGuid>93fb7162-3b6a-43bb-89db-574d4afd65aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;processing-options-form-submit-button&quot;)</value>
      <webElementGuid>7514b026-e09e-4f2f-ac8c-43f423d706f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='processing-options-form-submit-button']</value>
      <webElementGuid>e2a9cb48-1b80-4677-bcaa-9307854498bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='processing-options-form']/div/div[2]/input[2]</value>
      <webElementGuid>d491ca58-8708-4e59-bb0c-2293005b0d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>6c90b528-a53b-47fc-9d04-847320651dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'processing-options-form-submit-button']</value>
      <webElementGuid>dea13575-4603-42ee-a51d-9206e88dabb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
