<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_D5Gfqd4ssQ</name>
   <tag></tag>
   <elementGuidId>2a4b7a15-19c4-4266-9d7d-f67ebd615512</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#D5Gfqd4ssQ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='D5Gfqd4ssQ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9264b212-3aee-4621-8468-a63b45378268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>b61d1dad-1ca1-4085-8c0b-ee1220e573a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>D5Gfqd4ssQ</value>
      <webElementGuid>088c49c5-e4f3-48a4-83e8-ff7f69fe4000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>7eb2ca40-376e-4b71-a188-af4ef79fdb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b8f651e8-8f84-4795-b108-f9737e4fddf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;D5Gfqd4ssQ&quot;)</value>
      <webElementGuid>5a4a1899-da0c-4e1b-b6c2-1c95dd2e72fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='D5Gfqd4ssQ']</value>
      <webElementGuid>de4b48e4-3242-49a0-b0f9-1bd6abc76c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jCBSYBKHX-slds-tabs_panel-0']/div/div[3]/div/div/input</value>
      <webElementGuid>4cacee38-c7de-42e0-b4f3-d5741bd3c198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>14545167-ef09-4a94-a6dd-867c4a7b611e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'D5Gfqd4ssQ' and @placeholder = 'Search' and @type = 'text']</value>
      <webElementGuid>7307d10d-8e53-4853-aeaf-74036ffef966</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
