<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Processing</name>
   <tag></tag>
   <elementGuidId>e16a18d7-7803-4c31-8d54-0f0211a9f240</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='side-nav']/div[2]/li/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c60f0da5-ca0c-479b-9cf1-b0998d35a885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>side-navigation__action-text slds-m-left--x-small</value>
      <webElementGuid>a74c9964-66a3-426c-b74c-93a16deec211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Processing</value>
      <webElementGuid>286cd0a9-480c-41c4-9f97-adbd07ef7301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Processing</value>
      <webElementGuid>0037e429-ac89-458f-b0c0-a70f439bbd75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-nav&quot;)/div[@class=&quot;slds-nav-vertical__section slds-m-top--small&quot;]/li[@class=&quot;slds-nav-vertical__item&quot;]/a[@class=&quot;side-navigation__action slds-nav-vertical__action slds-p-vertical--small&quot;]/span[@class=&quot;side-navigation__action-text slds-m-left--x-small&quot;]</value>
      <webElementGuid>052ae422-3ab1-471c-a315-8bdb9c0519e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='side-nav']/div[2]/li/a/span[2]</value>
      <webElementGuid>28c3d01b-1988-4409-8c13-1f1ff8e7fecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options'])[1]/following::span[2]</value>
      <webElementGuid>33aeb9b6-c6d7-448e-a7fd-c9148d7bfe8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responses'])[1]/following::span[2]</value>
      <webElementGuid>b93872df-d9dd-4ecc-9eac-1e4c1d3a2cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/preceding::span[2]</value>
      <webElementGuid>9886073f-c30e-40fa-b1e9-33df337eef10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connectors'])[1]/preceding::span[4]</value>
      <webElementGuid>0220d811-9064-45f9-9fa9-d149245b04b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Processing']/parent::*</value>
      <webElementGuid>281b7af1-3d6d-42df-a121-2e238df8de28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/li/a/span[2]</value>
      <webElementGuid>a65abc17-61eb-4eb2-8bb3-36abc3d35adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Processing' or . = 'Processing')]</value>
      <webElementGuid>e631e2b2-5689-4fa9-a33e-300a2257faa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
